### ISSUE TITLE
GUI object labels are black in dark themes

### ISSUE THREAD

**Issue by jamshark70** [sebshader/color-themes-plugin#3]
Just trying this out -- installation was relatively painless, thanks!

I did observe that slider, toggle etc. labels are black even in dark themes. No time at the moment to dig into it but that would be a nice detail to adjust.

Great stuff here!

**Comment by sebshader** [comment]
Hi,
Right now I don't mess with any of the 'iemgui' stuff because they can be set from messages, and I want to break distributed abstractions as little as possible.
I think The basic issue is: it is impossible to know if an item is being created from the menu (or dynamically) or being loaded from a patch. Even if it is loaded from a patch the items would then have to be the default colors in the case of using them on a regular canvas, so this issue would persist.
I'm going to close this for now until some solution for this issue presents itself. Then perhaps there could be default colors for these things

**Comment by sebshader** [comment]
I'm also going to transfer this to pd-next because this is an issue w/ pd-next core, not the color theme picker
